-- 1. WAQTD 2ND MINIMUM SALARY
SELECT MIN(SAL)
FROM EMP
WHERE SAL > (
    SELECT MIN(SAL) FROM EMP
);

-- 2. WAQTD 5TH MAXIMUM SALARY
SELECT MAX(SAL)
FROM EMP
WHERE SAL < (
    SELECT MAX(SAL)
    FROM EMP
    WHERE SAL < (
        SELECT MAX(SAL)
        FROM EMP
        WHERE SAL < (
            SELECT MAX(SAL)
            FROM EMP
            WHERE SAL < (
                SELECT MAX(SAL)
                FROM EMP
            )
        )
    )
);

-- 3. WAQTD NAME OF THE EMPLOYEE EARNING MAXIMUM SALARY
SELECT ENAME
FROM EMP
WHERE SAL = (
    SELECT MAX(SAL) FROM EMP
);

-- 4. WAQTD EMPNO OF THE EMPLOYEE EARNING 2ND MAXIMUM SALARY
SELECT EMPNO
FROM EMP
WHERE SAL = (
    SELECT MAX(SAL)
    FROM EMP
    WHERE SAL < (
        SELECT MAX(SAL) FROM EMP
    )
);

-- 5. WAQTD DEPARTMENT NAME OF THE EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM EMP
    WHERE SAL = (
        SELECT MAX(SAL)
        FROM EMP
        WHERE SAL < (
            SELECT MAX(SAL) FROM EMP
        )
    )
);

-- 6. WAQTD 4TH MAX SALARY
SELECT MAX(SAL)
FROM EMP
WHERE SAL < (
    SELECT MAX(SAL)
    FROM EMP
    WHERE SAL < (
        SELECT MAX(SAL)
        FROM EMP
        WHERE SAL < (
            SELECT MAX(SAL)
            FROM EMP
        )
    )
);

-- 7. WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED LAST
SELECT *
FROM EMP
WHERE HIREDATE = (
    SELECT MAX(HIREDATE)
    FROM EMP
);

-- 8. WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST
SELECT LOC
FROM DEPT
WHERE DEPTNO = (
    SELECT DEPTNO
    FROM EMP
    WHERE HIREDATE = (
        SELECT MIN(HIREDATE)
        FROM EMP
    )
);

-- 9. WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED BEFORE THE EMPLOYEE WHO WAS HIRED FIRST
SELECT *
FROM EMP
WHERE HIREDATE < (
    SELECT MIN(HIREDATE)
    FROM EMP
);

-- 10. WAQTD NAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT ENAME
FROM EMP
WHERE SAL = (
    SELECT MAX(SAL)
    FROM EMP
    WHERE SAL < (
        SELECT MAX(SAL) FROM EMP
    )
);
